# Generated by Django 4.1.1 on 2022-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
